# Main config file for icon theme.
theme = "hugo-icon"
baseURL = "https://cloudeng.io/"
languageCode = "en-AU"
title = "cloudeng"

# Metadata
[params]
  author = "cloudeng"
  description = "Cosmos Nicolaou"

# Hero section (from here on is for icon theme)
[params.hero]
  img = "images/hero_bg.jpg"
  title = "cloudeng"
  description = "Technology, Leadership and Sofware Consulting"

# Navigation section
[params.nav]
  mission = "Mission"
  services = "Expertise"
  team = "People"
  contact = "Get In Touch"
  #  mission = "Our Mission"
  # Include logo instead if HOME:
  # logo = "path/to/logo"

# Mission section
[params.mission]
  enable = false

  [params.mission.images]
    enable = false

    [[params.mission.images.list]]
      img = "images/img_3.jpg"
    [[params.mission.images.list]]
      img = "images/img_2.jpg"
    [[params.mission.images.list]]
      img = "images/img_1.jpg"
    [[params.mission.images.list]]
      img = "images/img_4.jpg"

  [[params.mission.item]]
    weight = 1
    name = "marketing"
    title = "Marketing"
    subtitle = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione voluptate laborum sapiente officiis molestiaea."
    description = "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae aliquid aperiam eveniet officia molestiae temporibus beatae dolores dignissimos aspernatur eius doloremque ad, eaque pariatur, repellendus illum, nostrum velit necessitatibus molestias.</p><ul class='checked'><li>Web Development</li><li>User Interface Experts</li><li>Pixel Perfect Design</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

  [[params.mission.item]]
    weight = 2
    name = "analysis"
    title = "Resources"
    subtitle = "Quam quasi illum expedita dicta nemo fugit reprehenderit similique! Corporis praesentium magnam sequi."
    description = "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo, molestiae eaque fugiat dolores est esse, doloremque placeat assumenda corrupti officia dolorum. Sunt saepe ut, explicabo consectetur, nostrum illo est.</p><ul class='checked'><li>Free HTML5 Templates</li><li>Free Bootstrap Templates</li><li>Free HTML5 Bootstrap Templates</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

  [[params.mission.item]]
    weight = 3
    name = "strategy"
    title = "Strategy"
    subtitle = "Magnam iste obcaecati illo laboriosam amet. Dignissimos sed quis voluptatum corporis adipisci amet."
    description = "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio dolore illum expedita placeat debitis, dignissimos obcaecati et modi. Possimus id dicta consequuntur veritatis, reiciendis at expedita voluptate sint distinctio eligendi!</p><ul class='checked'><li>Web Development</li><li>User Interface Experts</li><li>Pixel Perfect Design</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

# Services section
[params.services]
  enable = true
  video = false
  title = "Areas of Expertise"
  description = ""

  [[params.services.item]]
    icon = "icon-compass"
    title = "Executive and Startup Leadership"
    description = "15+ years of VP and director level experience at Google, GRAIL, Akamai and FORE Systems. Founder, pre and post-IPO strategic planning and fund raising."

  [[params.services.item]]
    icon = "icon-google"
    title = "Internet Search"
    description = "Detailed knowledge of all aspects of internet search. Led the infrastructure teams for Google search from 2005 to 2012."

  [[params.services.item]]
    icon = "icon-barcode"
    title = "Next Generation Sequencing and Associated Computation"
    description = "Experience of NGS and in particular cell-free DNA/RNA analysis and computational methods. Led [GRAIL](https://grail.com)'s team that built the cloud processing tools and infrastructure some of which is available as opensource on [github](https://github.com/grailbio)."

  [[params.services.item]]
    icon = "icon-cloud"
    title = "Large Scale Ditributed Sytems and Cloud Computing"
    description = "20+ years of experience using and building large scale distributed sytems (ie. >1000s' of machines), including managing Google's infrastructure teams."

  [[params.services.item]]
    icon = "icon-link"
    title = "WWW, Internet and Networking Systems and Protocols"
    description = "Understanding and experience of core web internet and networking technologies. Practical experience will all aspects of the web and networking ranging from switching, routing and firewall technology, to TCP/IP, DNS, HTTP, HTML and most current web technologies and systems. Led the teams at Akamai that built the first internet scale streaming and storage services in the early 2000's. "

  [[params.services.item]]
    icon = "icon-chrome"
    title = "Consumer Web Properties"
    description = "Managed and contributed to many consumer web properties include product, UI, analyatics and all aspects of implementation; notably: Google news, image search, finance (when it was a standalone property), shopping (when it was froogle) and video before Google acquired youtube."

# Work section
[params.work]
  enable = false

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_1.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_4.jpg"

# Team section
[params.team]
  enable = true
  title = "Meet The Team"
  description = ""

  [[params.team.item]]
    name = "Cosmos Nicolaou"
    position = "Principal"
    description = "I have been fortunate to work in leadership positions at several notable and innovative companies ranging from startups, pre-IPO and public companies in the areas of distributed computing, computer networking, internet search, web properties, cloud computing and most recently next-generation DNA-sequencing for cancer screening."
    img = "{{.}}/images/Cos Nicolaou.jpg"
    github = "https://github.com/cosnicolaou"
    linkedin = "https://linkedin.com/in/cos-nicolaou"
    personal = "https://cosmosnicolaou.com"

# Contact section
[params.contact]
  enable = true
  title = "Get In Touch"
  message = "email <a href=\"mailto://info@cloudeng.io\">info@cloudeng.io</a>, or fill in the form below"
  name_placeholder = "your name"
  email_placeholder = "you@youremail.com"
  email_disclaimer = ""
  message_placeholder = "Please enter a message."
  button_text = "Submit"

# Footer section
# Note here that the copyright and attribution statement must remain as part of the license agreement. If you wish to remove this, please contact freehtml5 and pay for a professional license.
[params.footer]
  enable = true
  note = "<p><small>&copy; 2018. All Rights Reserved. cloudeng LLC."
  github = "https://github.com/cloudengio"
  
